### ISSUE TITLE
你的method tfidf , CFN-Vertex-Weight-TFIDF吃東西不吐骨頭0.0

### ISSUE THREAD

**Issue by xxcqc250** [UDICatNCHU/Behavior2Text#1]
如標題

**Comment by david30907d** [comment]
@xxcqc250  Sorry, 因為tfidf的method會去呼叫 [udicTF-IDF函式庫](https://github.com/udicatnchu/tf-idf)
而那個庫太久沒更新導致兩邊資料格式對不上QQ
以修正 3Q
